### ISSUE TITLE
Bottom Bar Error

### ISSUE THREAD

**Issue by Eternyt** [oeaeee/n1-stripe#5]
I'm not so good with english, so I try to explain my problem with a short video.
[Untitled.mov.zip](https://github.com/oeaeee/n1-stripe/files/288310/Untitled.mov.zip)
The Bottom bar is so caotic because i must use the two finger swipe to see all the things, and it's not static.

**Comment by oeaeee** [comment]
Thanks for this. Which OS are you using? I saw (and fixed) a similar issue a little while back, but I'm not seeing it at the moment.

**Comment by Eternyt** [comment]
I use a MacBook pro mid2014 with el capitain 10.11.4

**Comment by oeaeee** [comment]
I'm pretty sure what's going on is your Inbox list is expanded. In the standard N1 interface (you can see this if you use pretty much any theme except Stripe), when the user is viewing All Accounts, s/he can expand and collapse each category (Inbox, Starred, Snoozed, etc.). 

Because Stripe displays accounts horizontally, an expanded list breaks the UI. I'll work on a solution to prevent the poor layout. I'm leaning towards continuing to prevent the user from viewing expanded categories. It seems unnecessary given (1) the goal of showing accounts horizontally and (2) the content is accessible by changing the account.

To fix this in the short term, you could:
1. Change to one of the standard themes (ie. switch away from Stripe if you're using it).
2. Make sure you're viewing All Accounts (not an individual one).
3. In the accounts sidebar, make sure all the categories are collapsed (all arrows should point rightwards, not downwards).
![screen shot 2016-06-05 at 16 09 02](https://cloud.githubusercontent.com/assets/5192245/15808900/27649228-2b38-11e6-960b-ef20f471d66d.png)
4. Switch the theme to Stripe.

**Comment by oeaeee** [comment]
This is fixed with the latest. The workaround listed above shouldn't be necessary.

**Comment by Eternyt** [comment]
Very thanks, the lastest version have fix it!
